version: '3.0'

services:
  wordpress:
      image: wordpress:php7.1
      environment: 
        - WORDPRESS_DB_USER=wp_user
        - WORDPRESS_DB_PASSWORD=wp_password
        - WORDPRESS_DB_NAME=wordpress
      ports: 
        - 8080:80
      networks: 
        - wordpressnet
      
      volumes:
        - wordpressdata:/var/www/html

  mysql:
    image: mariadb:latest
    environment: 
        - MYSQL_USER=wp_user
        - MYSQL_ROOT_PASSWORD=wp_db_password 
        - MYSQL_DATABASE=wordpress 
        - MYSQL_PASSWORD=wp_password
    networks:
        - wordpressnet
    volumes:
        - mariadbdata:/var/lib/mysql
networks: 
  wordpressnet:
    driver: bridge

volumes:
  wordpressdata:
  mariadbdata:


      

    



